services:
  agent:
    image: ghcr.io/nwdock/nwdock-agent:latest
    restart: unless-stopped
    network_mode: host
    cap_add:
      - NET_BIND_SERVICE
    command:
      - -config
      - /etc/nowhere/agent.conf
    volumes:
      - agent-data:/var/lib/nowhere-agent
      - /etc/nowhere/agent.conf:/etc/nowhere/agent.conf:ro

volumes:
  agent-data:
